config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  post 'profile/upload_profile_photo'
  post 'profile/hide_painting/:id', to: 'profile#hide_painting', as: :hide_painting
  resources :profile

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@paintings = ActiveStorage::Attachment.where(name: "paintings").where(show: true)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= link_to "View Profile", profile_path(current_user), class: "btn btn-primary" if current_user.present? %>
<div class="container">
  <div class="row text-center">
    <% @paintings.each do |painting| %>      
        <div class="col-md-3">
          <a href="<%= profile_path(painting.record) %>" class="d-block mb-4 h-100">
            <%= image_tag painting, class: "img-fluid img-thumbnail" %>
            <%= painting.record.username %>
          </a>
        </div>
      
    <% end %>
  </div>

</div>

<div class="container">
  <div class="modal" id="login_register_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="tab-content">
            <div id="register" class="tab-pane fade">
              <%= render 'users/registrations/new' %>
            </div>
            <div id="login" class="tab-pane active">
              <% if flash[:alert].present? %>
                <p style="color: red;">
                  <%= flash[:alert] %>
                </p>
              <% end %>
              <%#= render 'login' %>
              <%= render 'users/sessions/new' %>
            </div>
            <div id="after_register" class="tab-pane fade">
              <%#= render 'after_register' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  <% if params[:controller] == "users/sessions" %>
    $(".login_register_button").trigger('click');
  <% end %>
</script>